spring:
  application:
    name: myshop-web
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    preferIpAddress: true
feign:
  hystrix:
    enabled: true